name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true

      - name: Run tests
        timeout-minutes: 5
        run: |
          ${{matrix.env}} bundle exec turbo_tests
